### PR TITLE
added aws batch

### PR DESCRIPTION
**Pull request by lh00000000**

### CODE REVIEW

**Comment by rkoval** [comment]
hey, just letting you know that i've seen this, but i need to actually set up a script that automatically will add this change to the bundled workflow. as-is, this edit to the `.csv` file won't actually affect the final `.alfredworkflow` file. i'll merge this whenever that script is ready

**Comment by lh00000000** [comment]
Sounds good!
I tried making the new workflow by importing into Alfred then exporting another .alfredworkflow file, but a script like that would be infinitely better.

**Comment by rkoval** [comment]
@lh00000000 - i finally got around to doing this. i ended up making a decent amount of changes to the repo such that this PR doesn't make as much sense anymore as-is.

HOWEVER, i did accommodate what your changes _would_ have looked like had conflicts and such been resolved. see 6c7919998292c634dd5b528836c4228bfb6def24 (notice that you are credited as the committer 😄 ). 

as such, i'm going to close this PR as "unmerged", but you can still grab the latest release with `batch` added to it here: https://github.com/rkoval/alfred-aws-console-services-workflow/releases/tag/v1.1 . sorry for the delay here!

**Comment by rkoval** [comment]
also, if you're wanting to make any changes going forward, have a look at: https://github.com/rkoval/alfred-aws-console-services-workflow#contributing

**Comment by lh00000000** [comment]
the new generation script looks great! 
thanks for the awesome work on this. I seriously use this thing 500 times a day.

**Comment by lh00000000** [comment]
Title


This is an invitation to participate in a performance—of which you are now the audience. To participate, click
click https://howdoesitfeeltobeafiction.org.
 
The email address you received this invitation from repeats the name of the person who last participated in the
performance. It is a mark of the work’s viral circulation. If you reply, your message will not be sent to the person
named as the sender but to the original author of this work.
 

Αυτή είναι μια πρόσκληση συμμετοχής σε μια περφόρμανς - της οποίας είστε τώρα το κοινό. Για να συμμετάσχετε, κάντε κλικ
στο https://howdoesitfeeltobeafiction.org.
 
Η διεύθυνση ηλεκτρονικού ταχυδρομείου από την οποία λάβατε αυτή την πρόσκληση επαναλαμβάνει το όνομα του ατόμου που
συμμετείχε τελευταίο στην περφόρμανς. Είναι ένα «σημάδι» της viral κυκλοφορίας του έργου. Αν απαντήσετε, το μήνυμά σας
δεν πρόκειται να αποσταλεί στο πρόσωπο που εμφανίζεται ως αποστολέας αλλά στον δημιουργό του έργου.

This piece by Aliza Shvarts is produced on the occasion of the 6th Athens Biennale ANTI // Το κομμάτι
    αυτό του Aliza
    Shvarts παράγεται με την ευκαιρία της 6ης Μπιενάλε της Αθήνας ANTI.

**Pull request closed without merging**
